# conda env create -f environment.yml
name: azureml
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.*
  - pip
  - jupyter

  # Model related
  - scikit-learn==0.20.3   # Same to the default in AzureML
  - joblib
  - pandas

  - pip:
    - azureml-core
    - azureml-dataprep[fuse,pandas]
    - azureml-pipeline
    - azureml-widgets
